# Generated by Django 4.0.4 on 2022-05-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
